language: node_js
node_js:
  - "8"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --nightly
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn -v
  - yarn add global create-react-app@2.0.1
  - create-react-app pnp-app --use-pnp
  - cat pnp-app/package.json
  - ls -la pnp-app